version: 0.2
phases:
  install:
    commands:
    - echo Entered the install phase...
    finally:
      - echo This always runs even if the install command fails 
  pre_build:
    commands:
    - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the pre-build command fails 
  build:
    commands:
    - java --version
    - chmod a+x gradlew
    - ./gradlew build
    finally:
      - echo This always runs even if the build command fails 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`   


artifacts:
  files:
  - build/libs/aws-sample-code-0.1.jar
  - appspec.yml
  - scripts/*
  discard-paths: true