version: 0.2

phases:
  build:
    commands:
      - chmod a+x gradlew
      - ./gradlew build
artifacts:
  files:
    - build/libs/aws-sample-code-0.1.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
