version: 0.2
phases:
  install:
    commands:
    - echo Entered the install phase...
    finally:
      - echo This always runs even if the install command fails 
  pre_build:
    commands:
    - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the pre-build command fails 
  build:
    commands:
    - java --version
    - chmod a+x gradlew
    - ./gradlew build
    finally:
      - echo This always runs even if the build command fails 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`   
      - ls -lrt 
      - pwd
      - cd build/distributions
      - unzip aws-sample-code-0.1.zip
      - ls -lrt 
      - rm -rf aws-sample-code-0.1.zip
      - ls -lrt 
      - cp /aws-sample-code-0.1 .
      - ls -lrt 


artifacts:
  files:
  - build/distributions/aws-sample-code-0.1.zip
  discard-paths: true